import { formatCents } from '@/lib/fees'
import type { ListingCardData } from '@/app/components/listing-card'

export type ProtoListing = ListingCardData & {
  description: string
  color: string
  shipping_display: string
  listed_line: string
  seller_handle: string
  seller_initials: string
  trust_line: string
  measurement_labels: string[]
  measurements: Record<string, number>
  sold?: boolean
}

type Seed = Omit<
  ProtoListing,
  'price_display' | 'images' | 'seller' | 'measurement_labels' | 'measurements' | 'shipping_display' | 'listed_line' | 'seller_initials'
> & {
  shipping_cents: number
  listed_ago: string
  chest?: number
  length?: number
  shoulder?: number
}

function listing(seed: Seed): ProtoListing {
  const initials = seed.seller_handle.slice(0, 2).toUpperCase()
  return {
    ...seed,
    images: [],
    price_display: formatCents(seed.price_cents),
    shipping_display: formatCents(seed.shipping_cents),
    listed_line: seed.listed_ago,
    seller: { username: seed.seller_handle, id_verification_status: 'verified' },
    seller_initials: initials,
    measurement_labels: ['CHEST', 'LENGTH', 'SHOULDER'],
    measurements: {
      ...(seed.chest != null ? { CHEST: seed.chest } : {}),
      ...(seed.length != null ? { LENGTH: seed.length } : {}),
      ...(seed.shoulder != null ? { SHOULDER: seed.shoulder } : {}),
    },
  }
}

export const PROTO_LISTINGS: ProtoListing[] = [
  listing({
    id: 'proto-01',
    title: 'Boxy wool overcoat with peak lapel',
    brand: 'The Row',
    category: 'Outerwear',
    department: 'womens',
    size: 'S',
    condition_score: 9,
    price_cents: 185000,
    original_price_cents: null,
    is_price_dropped: false,
    saves_count: 24,
    created_at: '2026-08-30T14:00:00.000Z',
    authentication_status: 'authenticated',
    promoted: true,
    color: 'Camel',
    description: 'Prototype listing — camel wool overcoat, lightly worn. Fixture data only; no live inventory.',
    seller_handle: 'atelier.east',
    trust_line: 'VERIFIED · 18 SALES',
    shipping_cents: 1500,
    listed_ago: 'LISTED 8D AGO',
    chest: 22,
    length: 44,
    shoulder: 17,
  }),
  listing({
    id: 'proto-02',
    title: 'Five-pocket raw denim jean',
    brand: 'Levi\'s',
    category: 'Bottoms',
    department: 'mens',
    size: '32',
    condition_score: 8,
    price_cents: 8900,
    original_price_cents: 12000,
    is_price_dropped: true,
    saves_count: 11,
    created_at: '2026-09-02T09:30:00.000Z',
    color: 'Indigo',
    description: 'Prototype listing — unsanforized denim, hemmed. Fixture data only.',
    seller_handle: 'archive.rail',
    trust_line: 'VERIFIED · 7 SALES',
    shipping_cents: 800,
    listed_ago: 'LISTED 5D AGO',
    length: 31,
  }),
  listing({
    id: 'proto-03',
    title: 'Tabi leather ankle boot',
    brand: 'Maison Margiela',
    category: 'Shoes',
    department: 'womens',
    size: '38',
    condition_score: 8,
    price_cents: 62000,
    original_price_cents: null,
    is_price_dropped: false,
    saves_count: 41,
    created_at: '2026-09-04T18:10:00.000Z',
    authentication_status: 'authenticated',
    color: 'Black',
    description: 'Prototype listing — split-toe leather boot, original box not included.',
    seller_handle: 'studio.north',
    trust_line: 'VERIFIED · 42 SALES',
    shipping_cents: 1800,
    listed_ago: 'LISTED 3D AGO',
  }),
  listing({
    id: 'proto-04',
    title: 'Crewneck heavyweight sweatshirt',
    brand: 'Champion',
    category: 'Tops',
    department: 'mens',
    size: 'L',
    condition_score: 7,
    price_cents: 4500,
    original_price_cents: null,
    is_price_dropped: false,
    saves_count: 6,
    created_at: '2026-09-05T11:00:00.000Z',
    color: 'Grey',
    description: 'Prototype listing — reverse-weave crew, faded mark at hem.',
    seller_handle: 'loft.sale',
    trust_line: '4 SALES',
    shipping_cents: 700,
    listed_ago: 'LISTED 2D AGO',
    chest: 24,
    length: 28,
    shoulder: 20,
  }),
  listing({
    id: 'proto-05',
    title: 'Pleated wool trouser',
    brand: 'Lemaire',
    category: 'Bottoms',
    department: 'womens',
    size: 'M',
    condition_score: 9,
    price_cents: 28000,
    original_price_cents: null,
    is_price_dropped: false,
    saves_count: 15,
    created_at: '2026-09-01T16:45:00.000Z',
    color: 'Stone',
    description: 'Prototype listing — high-rise wool trouser, dry cleaned.',
    seller_handle: 'atelier.east',
    trust_line: 'VERIFIED · 18 SALES',
    shipping_cents: 1000,
    listed_ago: 'LISTED 6D AGO',
    length: 40,
  }),
  listing({
    id: 'proto-06',
    title: 'Nylon bomber with rib cuff',
    brand: 'Alpha Industries',
    category: 'Outerwear',
    department: 'mens',
    size: 'M',
    condition_score: 8,
    price_cents: 16000,
    original_price_cents: 19000,
    is_price_dropped: true,
    saves_count: 9,
    created_at: '2026-08-28T08:20:00.000Z',
    color: 'Sage',
    description: 'Prototype listing — MA-1 style bomber, lining intact.',
    seller_handle: 'rail.west',
    trust_line: 'VERIFIED · 11 SALES',
    shipping_cents: 1200,
    listed_ago: 'LISTED 10D AGO',
    chest: 23,
    length: 26,
    shoulder: 19,
  }),
  listing({
    id: 'proto-07',
    title: 'Silk bias-cut slip dress',
    brand: 'Reformation',
    category: 'Dresses',
    department: 'womens',
    size: '4',
    condition_score: 9,
    price_cents: 14500,
    original_price_cents: null,
    is_price_dropped: false,
    saves_count: 19,
    created_at: '2026-09-06T13:15:00.000Z',
    color: 'Ivory',
    description: 'Prototype listing — bias slip, no pulls. Fixture data only.',
    seller_handle: 'studio.north',
    trust_line: 'VERIFIED · 42 SALES',
    shipping_cents: 900,
    listed_ago: 'LISTED 1D AGO',
    chest: 17,
    length: 48,
  }),
  listing({
    id: 'proto-08',
    title: 'Canvas low-top sneaker',
    brand: 'Veja',
    category: 'Shoes',
    department: 'mens',
    size: '42',
    condition_score: 7,
    price_cents: 7200,
    original_price_cents: null,
    is_price_dropped: false,
    saves_count: 5,
    created_at: '2026-09-03T20:00:00.000Z',
    color: 'White',
    description: 'Prototype listing — V-10, extra laces included.',
    seller_handle: 'loft.sale',
    trust_line: '4 SALES',
    shipping_cents: 800,
    listed_ago: 'LISTED 4D AGO',
  }),
  listing({
    id: 'proto-09',
    title: 'Cashmere crew sweater',
    brand: 'Khaite',
    category: 'Tops',
    department: 'womens',
    size: 'XS',
    condition_score: 10,
    price_cents: 34000,
    original_price_cents: null,
    is_price_dropped: false,
    saves_count: 27,
    created_at: '2026-09-06T21:40:00.000Z',
    authentication_status: 'authenticated',
    color: 'Black',
    description: 'Prototype listing — two-ply cashmere, unworn with tags.',
    seller_handle: 'atelier.east',
    trust_line: 'VERIFIED · 18 SALES',
    shipping_cents: 1000,
    listed_ago: 'LISTED 16H AGO',
    chest: 19,
    length: 23,
    shoulder: 16,
  }),
  listing({
    id: 'proto-10',
    title: 'Waxed cotton field jacket',
    brand: 'Barbour',
    category: 'Outerwear',
    department: 'mens',
    size: '38',
    condition_score: 6,
    price_cents: 11000,
    original_price_cents: null,
    is_price_dropped: false,
    saves_count: 3,
    created_at: '2026-08-20T12:00:00.000Z',
    color: 'Olive',
    description: 'Prototype listing — Bedale cut, lining worn at cuffs. Sold fixture for the veil.',
    seller_handle: 'rail.west',
    trust_line: 'VERIFIED · 11 SALES',
    shipping_cents: 1400,
    listed_ago: 'LISTED 18D AGO',
    sold: true,
    chest: 22,
    length: 29,
    shoulder: 18,
  }),
]

const BY_ID = new Map(PROTO_LISTINGS.map((l) => [l.id, l]))

export function getProtoListing(id: string): ProtoListing | undefined {
  return BY_ID.get(id)
}
